In [1]:
import numpy as np

In [2]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
l = range(1000)

In [10]:
%timeit [i**2 for i in l]

447 µs ± 31.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [11]:
a = np.arange(1000)
%timeit a**2

2 µs ± 56.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [13]:
b = np.array([[1,2,3], [3,4,5]])
b

array([[1, 2, 3],
       [3, 4, 5]])

In [14]:
b.ndim

2

In [15]:
b.shape

(2, 3)

In [16]:
len(b) # size of first dimentions

2

In [18]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [19]:
c.ndim

3

In [20]:
c.shape

(2, 2, 2)

In [21]:
b = np.arange(1,10,2)
b

array([1, 3, 5, 7, 9])

In [22]:
a = np.linspace(0,1,6) #start, end, number of points
a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [24]:
# common arrays
a = np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [25]:
a = np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [26]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
np.eye(3,2)

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [29]:
a = np.diag([1,2,3,4])
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [30]:
np.diag(a)

array([1, 2, 3, 4])

In [31]:
# create array using random

a = np.random.rand(4)
a

array([0.20188979, 0.88365241, 0.34926205, 0.67682193])

In [8]:
a = np.random.randn(4)
a

array([-1.13916527,  0.59226973,  0.14097627, -0.45755291])

In [10]:
a = np.arange(10, dtype= 'float64')
a.dtype

dtype('float64')

In [11]:
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [35]:
# the default type is float for zeros and ones

In [38]:
d = np.array([1+2j, 2+4j])
d
print(d.dtype)

complex128


In [42]:
b = np.array([True, False, True, False])
print(b.dtype)

bool


In [43]:
b

array([ True, False,  True, False])

In [48]:
a = np.array(["Rams", "Ram", "Rahim"])
a.dtype

dtype('<U5')

In [49]:
a = np.arange(10)

In [52]:
a = np.diag([1,2,3])
a[2,1]

0

In [53]:
a[2,1] = 5  #assigning value
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 5, 3]])

In [54]:
# Slicing

In [55]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
a[1:8:2] # start, end, step

array([1, 3, 5, 7])

In [57]:
# we can also combine assignment and slicing:
a = np.arange(10)
a[5:] = 10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [59]:
b = np.arange(5)
a[5:] = b[::-1] #-1 means reverseorder
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

In [60]:
# Copies and views

In [61]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
b = a[::2]
b

array([0, 2, 4, 6, 8])

In [65]:
np.shares_memory(a,b)# rather creating a copy of the array a, for space efficeinecy , it is just viewing

True

In [66]:
b[0] = 10
b

array([10,  2,  4,  6,  8])

In [67]:
a

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [68]:
#Work around is to use copy
a = np.arange(10)
c = a[::2].copy()
c

array([0, 2, 4, 6, 8])

In [69]:
np.shares_memory(a,c)

False

In [70]:
c[0] = 10
c

array([10,  2,  4,  6,  8])

In [71]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
# Fancy indexing

In [73]:
a = np.random.randint(0,20,15)
a

array([14,  9,  2,  5, 12,  9,  8,  4, 16,  6,  8, 11,  4,  9,  4])

In [74]:
mask = (a%2 == 0)
mask

array([ True, False,  True, False,  True, False,  True,  True,  True,
        True,  True, False,  True, False,  True])

In [75]:
extract_from_a = a[mask]
extract_from_a

array([14,  2, 12,  8,  4, 16,  6,  8,  4,  4])

In [77]:
a[mask] = -1
a

array([-1,  9, -1,  5, -1,  9, -1, -1, -1, -1, -1, 11, -1,  9, -1])

In [78]:
#    Indexing with an array of integers

In [79]:
a = np.arange(0,100,10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [80]:
a[[2,3,2,4,2]]

array([20, 30, 20, 40, 20])

In [81]:
a[[9,7]] = -200
a

array([   0,   10,   20,   30,   40,   50,   60, -200,   80, -200])

# Numpy operations Element wise

In [12]:
a = np.array([1,2,3,4])
a + 10

array([11, 12, 13, 14])

In [13]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [14]:
b = np.ones(4)+1
b

array([2., 2., 2., 2.])

In [88]:
a*b#  

array([2., 4., 6., 8.])

In [89]:
# Matrix utiplication

In [90]:
c = np.diag([1,2,3,4])
print(c*c)
print("*"*15)
print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
***************
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [91]:
a = np.array([1,2,3,4])
b = np.array([5,2,2,4])
a == b

array([False,  True, False,  True])

In [92]:
a > b

array([False, False,  True, False])

In [93]:
# array_wise comparisions
a = np.array([1,2,3,4,])
b = np.array([1,2,3,3,])
c = np.array([1,2,3,3,])
np.array_equal(a,b)

False

In [94]:
np.array_equal(b,c)

True

In [95]:
# Math operations

In [97]:
a = np.arange(5)
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [98]:
np.log(a)

c:\users\citrix\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [99]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

# Shape Mismatch

In [100]:
a = np.arange(4)
a+np.array([1,2])

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

In [101]:
#Basic Reductions

In [103]:
a = np.array([1,2,3,4])
np.sum(a)

10

In [104]:
 # sum by rows and by columns
    
x = np.array([[1,2], [3, 4]])
x

array([[1, 2],
       [3, 4]])

In [105]:
x.sum(axis = 0) # columns first dimension

array([4, 6])

In [106]:
x.sum(axis = 1) # rows second dimension

array([3, 7])

In [107]:
# other redcutouns

x = np.array([1,2,3])
x.min()

1

In [108]:
x.argmin() # index of min element

0

In [109]:
x.argmax()  # index of max element

2

In [110]:
# Logical Operations

In [111]:
np.all([True, True, False])

False

In [112]:
np.any([True, True, False])

True

In [113]:
a = np.zeros((50,50))
np.any(a!=0)

False

In [114]:
np.all(a==a)

True

In [115]:
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])
c = np.array([6,4,5,3])
((a<=b) & (b<=c)).all()

False

In [116]:
 # Statistics

In [21]:
x = np.array([1,2,3,1])
y = np.array([[1,2,3],[4,5,6],[4,7,6]])
x.mean()

1.75

In [118]:
y.mean()

3.5

In [119]:
y.mean()

3.5

In [23]:
np.median(y, axis = 0) # rows

array([4., 5., 6.])

# Broadcasting

In [121]:
# element wise 

In [123]:
a = np.tile(np.arange(0,40,10),(2,1))
print(a)

[[ 0 10 20 30]
 [ 0 10 20 30]]


In [24]:
a = np.tile(np.arange(0,40,10),(3,))
print(a)

[[ 0 10 20 30  0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30  0 10 20 30]]


In [52]:
a = np.tile(np.arange(0,50,10),(3,1))
print(a)


[[ 0 10 20 30 40]
 [ 0 10 20 30 40]
 [ 0 10 20 30 40]]


In [53]:
a = a.T
a

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30],
       [40, 40, 40]])

In [33]:
b = np.array([0,1,2])
b

array([0, 1, 2])

In [34]:
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32],
       [40, 41, 42]])

In [39]:
a[:, :1]

array([[ 0],
       [10],
       [20],
       [30],
       [40]])

In [40]:
a[:, :1]  + b 

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32],
       [40, 41, 42]])

In [147]:
a = np.arange(0,40,10)
a

array([ 0, 10, 20, 30])

In [54]:
a.shape

(5, 3)

In [57]:
a = a[:,np.newaxis] # converitng 1d array to 2d
a.shape

(5, 1, 1, 3)

In [58]:
 a

array([[[[ 0,  0,  0]]],


       [[[10, 10, 10]]],


       [[[20, 20, 20]]],


       [[[30, 30, 30]]],


       [[[40, 40, 40]]]])

# # Array Manipulations

In [59]:
a = np.array([[1,2,3],[4,5,6]])
a.ravel() # Return a contiguous flattened array, A 1-D array, containing the

array([1, 2, 3, 4, 5, 6])

In [60]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [75]:
np.random.normal(0.1,3,2000).std()

2.983466182368795

In [61]:
a.T.ravel()

array([1, 4, 2, 5, 3, 6])

In [62]:
# Reshape
a

array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
b = a.ravel()
b

array([1, 2, 3, 4, 5, 6])

In [64]:
b = b.reshape(2, 3)
b

array([[1, 2, 3],
       [4, 5, 6]])

In [65]:
b[0, 0] = 100
a

array([[100,   2,   3],
       [  4,   5,   6]])

In [66]:
#reshape may also return a copy

a = np.zeros((3,2))
b = a.T.reshape(3*2)
b[0] = 50
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [67]:
b

array([50.,  0.,  0.,  0.,  0.,  0.])

In [160]:
# Adding a diemnsion

In [68]:
z = np.array([1,2,3])
z

array([1, 2, 3])

In [69]:
z[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [163]:
# Dimension  Shuffling

In [165]:
a = np.arange(4*3*2).reshape(4,3,2)  # 4 matrices with 3 rows and 2 columns
a.shape

(4, 3, 2)

In [166]:
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [167]:
a[0, 2, 1]

5

In [168]:
#Resizing

In [169]:
a = np.arange(4)
a.resize((8, ))
a

array([0, 1, 2, 3, 0, 0, 0, 0])

In [170]:
b = a
a.resize((4,))

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

In [70]:
# Sorting data
a = np.array([[4,2,3], [2,4,1]])
b = np.sort(a, axis= 0)
b

array([[2, 2, 1],
       [4, 4, 3]])

In [173]:
# inplace sort
a.sort(axis = 1)
a

array([[2, 3, 4],
       [1, 2, 4]])

In [174]:
# sorting with fancy indexing
a = np.array([4,3,1,2])
j = np.argsort(a)
j

array([2, 3, 1, 0], dtype=int64)

In [175]:
 a[j]

array([1, 2, 3, 4])

In [ ]:
# Numpy

In [3]:
import numpy as np

In [4]:
b = np.array([[1.0,2.0],[3, 4]])
b

array([[1., 2.],
       [3., 4.]])

In [5]:
b.itemsize

8

In [ ]:
# get total size

In [7]:
b.nbytes

32

In [77]:
class A:
    def _init__(self):
        print("A")
class B(A):
    pass
c =B()


TypeError: 'B' object is not callable

In [ ]:
a[:, :1]

# Pandas

In [181]:
import pandas as pd
df = pd.read_csv('nyc_weather.csv')
df

date  maximum temperature  minimum temperature  \
0      1-1-2016                   42                   34   
1      2-1-2016                   40                   32   
2      3-1-2016                   45                   35   
3      4-1-2016                   36                   14   
4      5-1-2016                   29                   11   
..          ...                  ...                  ...   
361  27-12-2016                   60                   40   
362  28-12-2016                   40                   34   
363  29-12-2016                   46                   33   
364  30-12-2016                   40                   33   
365  31-12-2016                   44                   31   

     average temperature precipitation snow fall snow depth  
0                   38.0          0.00       0.0          0  
1                   36.0          0.00       0.0          0  
2                   40.0          0.00       0.0          0  
3                   25.0          0.00       0.0          0  
4                   20.0          0.00       0.0          0  
..                   ...           ...       ...        ...  
361                 50.0             0         0          0  
362                 37.0             0         0          0  
363                 39.5          0.39         0          0  
364                 36.5          0.01         T          0  
365                 37.5             0         0          0  

[366 rows x 7 columns]

In [178]:
df.columns

Index(['date', 'maximum temperature', 'minimum temperature',
       'average temperature', 'precipitation', 'snow fall', 'snow depth'],
      dtype='object')

In [179]:
df['maximum temperature'].max()

96

In [183]:
df['date'][df['maximum temperature'] > 50]

9       10-1-2016
14      15-1-2016
15      16-1-2016
30      31-1-2016
31       1-2-2016
          ...    
334    30-11-2016
335     1-12-2016
336     2-12-2016
352    18-12-2016
361    27-12-2016
Name: date, Length: 272, dtype: object

In [184]:
#PD dataframe
import pandas as pd
df = pd.read_csv('nyc_weather.csv')
df

date  maximum temperature  minimum temperature  \
0      1-1-2016                   42                   34   
1      2-1-2016                   40                   32   
2      3-1-2016                   45                   35   
3      4-1-2016                   36                   14   
4      5-1-2016                   29                   11   
..          ...                  ...                  ...   
361  27-12-2016                   60                   40   
362  28-12-2016                   40                   34   
363  29-12-2016                   46                   33   
364  30-12-2016                   40                   33   
365  31-12-2016                   44                   31   

     average temperature precipitation snow fall snow depth  
0                   38.0          0.00       0.0          0  
1                   36.0          0.00       0.0          0  
2                   40.0          0.00       0.0          0  
3                   25.0          0.00       0.0          0  
4                   20.0          0.00       0.0          0  
..                   ...           ...       ...        ...  
361                 50.0             0         0          0  
362                 37.0             0         0          0  
363                 39.5          0.39         0          0  
364                 36.5          0.01         T          0  
365                 37.5             0         0          0  

[366 rows x 7 columns]

In [186]:
df.columns

Index(['date', 'maximum temperature', 'minimum temperature',
       'average temperature', 'precipitation', 'snow fall', 'snow depth'],
      dtype='object')

In [187]:
df['maximum temperature'].describe()

count    366.000000
mean      64.625683
std       18.041787
min       15.000000
25%       50.000000
50%       64.500000
75%       81.000000
max       96.000000
Name: maximum temperature, dtype: float64

In [189]:
#select rows whcih has maximum temperature
df[df.temperature == df.temperature.max()]


In [ ]:
#select only day  column whcih has max temperature
df.day[df.temperature == df.temperature.max()]

In [ ]:
# Reading csv and xls files

In [190]:
# Groupby
df.columns

Index(['date', 'maximum temperature', 'minimum temperature',
       'average temperature', 'precipitation', 'snow fall', 'snow depth'],
      dtype='object')

In [ ]:
g = df.groupby('city')
g

In [ ]:
for city, city_df in g:
    print(city)
    print(city_df)

In [ ]:
# get specific group
g.get_group('mumbai')

In [ ]:
# find maximum temperature in each of the cities
print(g.max())

In [ ]:
print(g.mean())

In [191]:
# Concatenate of DFs

In [ ]:
df = pd.concat([df_1, df_2]) # indicies are copied from the base dataframe

In [ ]:
df = pd.concat([df_1, df_2], ignore_index = True) #
df

In [ ]:
#columns wise concat(stacking side by side)
df = df.concat([df_1, df_2], axis = 1)
df

In [193]:
#Merge DataFrames
df = pd.merge(df_1, df_2, on='city')
# if a city is  present in the df_1 and not present in df_2, that
# row will be dropped.

In [ ]:
#Outer join
df = pd.merge(df_1, df_2, on = 'city', how = 'outer')
# from the above cell, the city is dropped, here using outer, 
# we can have have the city with Nan values

In [ ]:
# Numerical indexing
s.loc[46]
#when using loc we are using index number to extarct the data

In [ ]:
s.iloc[3]
#when using iloc we are using the row number to extract data