In [ ]:
!pip install torchvision

In [ ]:
from __future__ import print_function
import torch

In [ ]:
x = torch.empty(5,3)
print(x)

tensor([[8.8099e-36, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 0.0000e+00]])


In [ ]:
#Random intialized matrix
x = torch.rand(5, 3)
print(x)

tensor([[0.1629, 0.6169, 0.5775],
        [0.0684, 0.5430, 0.4389],
        [0.1826, 0.7198, 0.2915],
        [0.9404, 0.8375, 0.3876],
        [0.7381, 0.2789, 0.5999]])


In [ ]:
#a tensor with zeros and dtype long
x = torch.zeros(3, 3,  dtype=torch.long )
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [ ]:
x = torch.tensor([2, 4])
print(x)

tensor([2, 4])


In [ ]:
# x = x.new_ones(4, 3, dtype=torch.int)
# print(x)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)


In [ ]:
# properties like shape are used to create a new matrix, overrsing the dtype can be done
x = torch.rand_like(x, dtype=torch.long)
print(x)

RuntimeError: ignored

In [ ]:
print(x.size())

torch.Size([2])


In [ ]:
#operations
y = torch.rand(5,2)
x = torch.ones(5,2)
print(x+y)

tensor([[1.0393, 1.8096],
        [1.5014, 1.1252],
        [1.1722, 1.8822],
        [1.3691, 1.8185],
        [1.3363, 1.0249]])


In [ ]:
torch.add(x, y)

tensor([[1.0393, 1.8096],
        [1.5014, 1.1252],
        [1.1722, 1.8822],
        [1.3691, 1.8185],
        [1.3363, 1.0249]])

In [ ]:
#output as an argument
res = torch.empty(5,3)
torch.add(x,y, out=res)
print(res)

tensor([[1.0393, 1.8096],
        [1.5014, 1.1252],
        [1.1722, 1.8822],
        [1.3691, 1.8185],
        [1.3363, 1.0249]])


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: UserWarning: An output with one or more elements was resized since it had shape [5, 3], which does not match the required output shape [5, 2].This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at  /pytorch/aten/src/ATen/native/Resize.cpp:19.)
  This is separate from the ipykernel package so we can avoid doing imports until


In [ ]:
#inplace addition
#adding x to y
y.add_(x)
y

tensor([[1.0393, 1.8096],
        [1.5014, 1.1252],
        [1.1722, 1.8822],
        [1.3691, 1.8185],
        [1.3363, 1.0249]])

In [ ]:
# an operation whihc alters a tensor in place just like add_ in th eabove cell, will have _ as postfix element
# x.copy_(y), x.t_() will alter x


In [ ]:
x = torch.rand(4,3)
x

tensor([[0.7829, 0.9555, 0.9019],
        [0.1665, 0.3240, 0.9307],
        [0.0443, 0.7856, 0.4806],
        [0.7510, 0.0822, 0.2482]])

In [ ]:
x[:, 1]# all rows and second column

tensor([0.9555, 0.3240, 0.7856, 0.0822])

In [2]:
# torch .view to reshape a tensor
import torch
x = torch.randn(5,4)# random numbers from noraml distribution
y = x.view(2, 10)
print(x)
print(y)

tensor([[ 2.1286,  0.4173,  1.3890,  1.4951],
        [ 1.4935,  0.5690,  1.5942, -1.3602],
        [-0.3482, -0.7607,  0.8125, -0.4509],
        [-0.1261, -0.9839, -0.3758, -0.1618],
        [-0.3266,  0.5949, -0.7069, -0.1459]])
tensor([[ 2.1286,  0.4173,  1.3890,  1.4951,  1.4935,  0.5690,  1.5942, -1.3602,
         -0.3482, -0.7607],
        [ 0.8125, -0.4509, -0.1261, -0.9839, -0.3758, -0.1618, -0.3266,  0.5949,
         -0.7069, -0.1459]])


In [3]:
torch.empty(5,3)

tensor([[3.1998e-36, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 6.4460e-44],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 0.0000e+00]])

In [ ]:
z = x.view(-1, 10)#  we only give one dimension, -1 will infer the other dimenion
print(x.size(), y.size(), z.size())

torch.Size([5, 4]) torch.Size([20]) torch.Size([2, 10])


In [6]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.7860])
0.785963773727417


In [7]:
#numpy
x = torch.ones(5)
x

tensor([1., 1., 1., 1., 1.])

In [ ]:
z = x.numpy()
z

array([1., 1., 1., 1., 1.], dtype=float32)

In [ ]:
x.add_(2)
print(x)
print(z)

tensor([3., 3., 3., 3., 3.])
[3. 3. 3. 3. 3.]


In [ ]:
# np to torch tensor
import numpy as np
import torch
a = np.ones(3)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)


[2. 2. 2.]
tensor([2., 2., 2.], dtype=torch.float64)


In [ ]:
# cuda tensors
if torch.cuda.is_available():
    device = torch.device("cuda")
    u = torch.ones_like(x, device=device)
    x = x.to(device) # or can use x.to("cuda")
    z =x+u
    print(z)
    print(z.to("cpu", torch.int))# .to can override the dtype

tensor([[ 2.3924,  2.3424,  0.3032,  1.2273],
        [ 0.1411,  0.0409, -0.1090,  2.2684],
        [ 0.0241,  1.2749, -0.4514, -0.1394],
        [ 1.6286,  0.7326,  0.0488,  0.7162],
        [ 1.7757,  1.7384,  0.7669, -1.0800]], device='cuda:0')
tensor([[ 2,  2,  0,  1],
        [ 0,  0,  0,  2],
        [ 0,  1,  0,  0],
        [ 1,  0,  0,  0],
        [ 1,  1,  0, -1]], dtype=torch.int32)


In [1]:
#20 Nov

import torch
x = torch.ones(2,2,requires_grad = True)
print(x)



tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [2]:
z = x + 3
print(z)

tensor([[4., 4.],
        [4., 4.]], grad_fn=<AddBackward0>)


In [3]:
y = z**2
out = y.mean()
print(z)
print(out)

tensor([[4., 4.],
        [4., 4.]], grad_fn=<AddBackward0>)
tensor(16., grad_fn=<MeanBackward0>)


In [5]:
a = torch.randn(2, 2)
a = ((a*3/(a-2)))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a*a).sum()
print(b.grad_fn)

False
True


In [6]:
b.requires_grad

True

In [7]:
out.backward()

In [8]:
x.grad

tensor([[2., 2.],
        [2., 2.]])

In [1]:
# CNN

import torch 
import torchvision
import torchvision.transforms as transforms

In [3]:
transform = transforms.Compose([transforms.ToTensor(), transforms.Normalize((0.5, 0.5, 0.5),(0.5, 0.5, 0.5))])
transform

Compose(
    ToTensor()
    Normalize(mean=(0.5, 0.5, 0.5), std=(0.5, 0.5, 0.5))
)

In [9]:
trainset =  torchvision.datasets.CIFAR10(root = './data', train = True, download = True, transform =transform )
print(trainset)
trainloader = torch.utils.data.DataLoader(trainset, batch_size=4, shuffle=True, num_workers = 2)

testset = torchvision.datasets.CIFAR10( root = './data', train =False, download=True, transform =transform )

testloader = torch.utils.data.DataLoader(testset, batch_size=4, shuffle= False, num_workers = 2)

classes = ('plane', 'car', 'bird', 'cat', 'deer', 'dog', 'frog', 'horse', 'ship', 'truck')

Files already downloaded and verified
Dataset CIFAR10
    Number of datapoints: 50000
    Root location: ./data
    Split: Train
    StandardTransform
Transform: Compose(
               ToTensor()
               Normalize(mean=(0.5, 0.5, 0.5), std=(0.5, 0.5, 0.5))
           )
Files already downloaded and verified


In [10]:
# Def cnn
import torch.nn as nn
import torch.nn.functional as F

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(3, 6, 5)
        self.pool = nn.MaxPool2d(2, 2)
        self.conv2 = nn.Conv2d(6, 16, 5)
        self.fc1 = nn.Linear(16*5*5, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)
    def forward(self, x):
        x = self.pool(F.relu(self.conv1(x)))
        x = self.pool(F.relu(self.conv2(x)))
        x = x.view(-1, 16*5*5)
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

net = Net()

In [18]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
print(device)
net.to(device)

cuda:0


Net(
  (conv1): Conv2d(3, 6, kernel_size=(5, 5), stride=(1, 1))
  (pool): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (conv2): Conv2d(6, 16, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=400, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)

In [21]:
import torch.optim as optim
criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(net.parameters(), lr = 0.001, momentum = 0.9)
optimizer

SGD (
Parameter Group 0
    dampening: 0
    lr: 0.001
    momentum: 0.9
    nesterov: False
    weight_decay: 0
)

In [24]:
#Train 

for epoch in range(3):
    running_loss = 0.0
    for i, data in enumerate(trainloader, 0):
        inputs, labels = data[0].to(device), data[1].to(device)
        optimizer.zero_grad()

        outputs = net(inputs)
        loss = criterion(outputs, labels)
        loss.to(device)
        loss.backward()
        optimizer.step()

        running_loss += loss.item()

        if i%2000 == 1999:
            print('[%d, %5d] loss: %.3f' % (epoch+1, i+1, running_loss/2000))
            running_loss = 0.0

print("Done training")

[1,  2000] loss: 1.071
[1,  4000] loss: 1.085
[1,  6000] loss: 1.087
[1,  8000] loss: 1.065
[1, 10000] loss: 1.073
[1, 12000] loss: 1.057
[2,  2000] loss: 0.997
[2,  4000] loss: 1.001
[2,  6000] loss: 1.001
[2,  8000] loss: 0.986
[2, 10000] loss: 1.015
[2, 12000] loss: 1.024
[3,  2000] loss: 0.915
[3,  4000] loss: 0.950
[3,  6000] loss: 0.934
[3,  8000] loss: 0.967
[3, 10000] loss: 0.955
[3, 12000] loss: 0.967
Done training
